version: '3.4'

services:
    moneytransaction.service:
        image: ${DOCKER_REGISTRY-}moneytransactionservice
        build:
            context: .
            dockerfile: MoneyTransaction/Dockerfile
        depends_on: 
            - "postgres"
        networks: 
            - aspnetcoreapp-network

    postgres:
        container_name: 'postgres'
        image: postgres
        environment:
            POSTGRES_USER: "bankingUser"
            POSTGRES_PASSWORD: "bankingUser"
            POSTGRES_DB: "bankingDb"
        networks:
            - aspnetcoreapp-network
        volumes:
            - ./DbScripts/createDb.sql:/docker-entrypoint-initdb.d/createDb.sql
networks:
  aspnetcoreapp-network:
    driver: bridge
