CREATE ROLE "bankingUser" WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'bankingUser';

CREATE DATABASE "bankingDb"
    WITH 
    OWNER = "bankingUser"
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;